name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ls
        run: ls -al

      - name: touch
        run: touch file

      - name: ls
        run: ls -al
