name: merge

on:
  push:
    branches: ['master']

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy-to-latest:
    uses: ./.github/workflows/deploy.yaml
    needs: build
    with:
      stage: latest
